### ISSUE TITLE
События с пользователями

### ISSUE THREAD

**Issue by AnatolyMoiseev** [playa-ru/keycloak-kafka-provider#2]
Добрый день, а через этот функционал можно вылавливать события над пользователями, которые происходят в адм консоли кейклока?

**Comment by hrensgory** [comment]
Да, все события, которые есть в KC стандартно - все можно получать.  Вас, как я понимаю, интересуют Admin Events. Надо включить их сохранение и наш Event Listener и они пойдут в Кафку.

Учтите, что в самом событии информация в основном представлена UUID объектов, так что на приёмнике вам, скорее всего, придётся по UUID получать из KC названия объектов и другие их атрибуты (это можно сделать через REST API KC) 

![изображение](https://github.com/playa-ru/keycloak-kafka-provider/assets/9786770/897594be-d497-43a7-8198-ab170f0fc512)


![изображение](https://github.com/playa-ru/keycloak-kafka-provider/assets/9786770/84e6f8dd-8204-4ece-9843-59f96d72ba50)
